app/main/forms.py
'''T5_cargogen forms.py'''

import re
import logging
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import Regexp, Optional

LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.ERROR)

UWP_REGEXP = r'^[A-HYX][0-9A-HJ-NP-Z]{6}\-[0-9A-HJ-NP-Z]$'
UWPS_REGEXP = r'\b[A-HYX][0-9A-HJ-NP-Z]{6}\-[0-9A-HJ-NP-Z]\b'


class SourceWorldForm(FlaskForm):
    '''Source world'''
    source_uwp = StringField(
        'Source world UWP',
        validators=[Regexp(UWP_REGEXP)])
    market_uwp = StringField(
        'Market world UWP',
        validators=[
            Optional()])
    submit = SubmitField('Submit')

    @staticmethod
    def validate_market_uwp(form, field):
        '''Custom validator to match multiple UWPs'''
        uwps = re.findall(UWPS_REGEXP, field.data)
        LOGGER.debug('uwps = %s', uwps)
        if len(uwps) == 0:
            msg = 'Invalid UWP or UWPs in {}'.format(
                field.data)
            raise ValidationError(msg)
        else:
            field.data = ' '.join(uwps)
            LOGGER.debug('%s.data = %s', field.name, field.data)

app/__init__.py
'''T5_cargogen app/__init__.py'''

import logging
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config


LOGGER = logging.getLogger(__name__)
logging.basicConfig(
    # format='%(asctime)-15s %(name)s %(funcName)s(): %(message)s',
    format='%(relativeCreated)d %(name)s %(funcName)s(): %(message)s',
    level=logging.INFO
)

bootstrap = Bootstrap()


def create_app(config_name):
    '''Create app'''
    LOGGER.debug('Setting up app %s', __name__)
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
'''
T5 cargo generator
'''

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
'''T5_cargogen views.py'''

import logging
from flask import render_template
from . import main
from .forms import SourceWorldForm

from .simple import TradeCargo
from .trade_codes import TradeCodes, Uwp

LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.ERROR)


class World(object):
    '''World class'''
    def __init__(self, uwp):
        self.uwp = Uwp(uwp)
        LOGGER.debug('uwp = %s', uwp)
        LOGGER.debug('self.uwp = %s', self.uwp)
        self.trade_codes = TradeCodes(self.uwp)
        LOGGER.debug('self.trade_codes = %s', self.trade_codes)


@main.route('/', methods=['GET', 'POST'])
def index():
    '''Generate cargo'''
    cargo = TradeCargo()
    form = SourceWorldForm()
    source_world_uwp = ''
    source_world_tcs = ''
    results = list()
    if form.validate_on_submit():
        LOGGER.debug('form.source_uwp.data = %s', form.source_uwp.data)
        # form.uwp.data is unicode, convert
        if form.source_uwp.data:
            source_world = World(str(form.source_uwp.data))
            cargo.generate_cargo(
                str(source_world.uwp),
                source_world.trade_codes.list())
            source_world_uwp = str(source_world.uwp)
            source_world_tcs = str(source_world.trade_codes)
        if form.market_uwp.data:
            LOGGER.debug('form.market_uwp.data = %s', form.market_uwp.data)
            for uwp in form.market_uwp.data.split(' '):
                LOGGER.debug('uwp = %s', uwp)
                market_world = World(str(uwp))
                cargo.generate_sale(
                    str(market_world.uwp),
                    market_world.trade_codes.list())
                results.append([
                    str(market_world.uwp),
                    str(market_world.trade_codes), cargo.str_price()])

    LOGGER.debug('results = %s', results)
    return render_template(
        'index.html',
        cargo=cargo,
        source_world_uwp=source_world_uwp,
        source_world_tcs=source_world_tcs,
        results=results,
        form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}T5 Cargogen{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">T5 Cargogen</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}T5 Cargo Generator{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
            data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">T5 Cargo Generator</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="Home"></a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>T5 Cargo Generator</h1>
    </div>
    <div class="body">
        {{ wtf.quick_form(form) }}
        <h3>Planet details</h3>
        <table width="75%" cellpadding="10">
            <tr>
                <th>Planet</th><th>UWP</th><th>Trade codes</th><th>Cargo</th>
            </tr>
            <tr>
                <td>Source</td>
                <td>{{ source_world_uwp }}</td>
                <td>{{ source_world_tcs }}</td>
                <td>{{ cargo.str_cost() }}</td>
            </tr>
        
            {% for f in results %}
            <tr>
                <td>            
                    Market
                </td>
                <td>
                    {{ f[0] }}
                </td>
                <td>
                    {{ f[1] }}
                </td>
                <td>
                    {{ f[2] }}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}